# coding: utf-8

"""
    UniCourt Enterprise APIs

    <button><a href=\"/developers/enterpriseapi/api/download/UniCourt-Enterprise-API-Spec.yaml\" >Download UniCourt Enterprise APIs Specification</a></button> 

    The version of the OpenAPI document: 
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from unicourt.models.bar_source_data_law_school_array_inner import BarSourceDataLawSchoolArrayInner

class TestBarSourceDataLawSchoolArrayInner(unittest.TestCase):
    """BarSourceDataLawSchoolArrayInner unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> BarSourceDataLawSchoolArrayInner:
        """Test BarSourceDataLawSchoolArrayInner
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `BarSourceDataLawSchoolArrayInner`
        """
        model = BarSourceDataLawSchoolArrayInner()
        if include_optional:
            return BarSourceDataLawSchoolArrayInner(
                law_school = '',
                law_school_graduated_date = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f')
            )
        else:
            return BarSourceDataLawSchoolArrayInner(
                law_school = '',
                law_school_graduated_date = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
        )
        """

    def testBarSourceDataLawSchoolArrayInner(self):
        """Test BarSourceDataLawSchoolArrayInner"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
