# coding: utf-8

"""
    UniCourt Enterprise APIs

    <button><a href=\"/developers/enterpriseapi/api/download/UniCourt-Enterprise-API-Spec.yaml\" >Download UniCourt Enterprise APIs Specification</a></button> 

    The version of the OpenAPI document: 
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from unicourt.models.additional_levels import AdditionalLevels

class TestAdditionalLevels(unittest.TestCase):
    """AdditionalLevels unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> AdditionalLevels:
        """Test AdditionalLevels
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `AdditionalLevels`
        """
        model = AdditionalLevels()
        if include_optional:
            return AdditionalLevels(
                object = 'AdditionalLevels',
                level1 = '0',
                level2 = '0',
                level3 = '0',
                level4 = '0'
            )
        else:
            return AdditionalLevels(
                object = 'AdditionalLevels',
                level1 = '0',
                level2 = '0',
                level3 = '0',
                level4 = '0',
        )
        """

    def testAdditionalLevels(self):
        """Test AdditionalLevels"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
