# coding: utf-8

"""
    UniCourt Enterprise APIs

    <button><a href=\"/developers/enterpriseapi/api/download/UniCourt-Enterprise-API-Spec.yaml\" >Download UniCourt Enterprise APIs Specification</a></button> 

    The version of the OpenAPI document: 
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from unicourt.models.document_download import DocumentDownload

class TestDocumentDownload(unittest.TestCase):
    """DocumentDownload unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> DocumentDownload:
        """Test DocumentDownload
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `DocumentDownload`
        """
        model = DocumentDownload()
        if include_optional:
            return DocumentDownload(
                object = 'DocumentDownload',
                case_document_id = '01234567891011121314151617',
                expiry_date = '0123456789101112131415161718192021222324',
                file_url = '0',
                case_document_download_api = '0',
                exception = unicourt.models.exception.Exception(
                    object = 'Exception', 
                    code = '0', 
                    message = '0', 
                    details = '0', )
            )
        else:
            return DocumentDownload(
                object = 'DocumentDownload',
                case_document_id = '01234567891011121314151617',
                expiry_date = '0123456789101112131415161718192021222324',
                file_url = '0',
                case_document_download_api = '0',
                exception = unicourt.models.exception.Exception(
                    object = 'Exception', 
                    code = '0', 
                    message = '0', 
                    details = '0', ),
        )
        """

    def testDocumentDownload(self):
        """Test DocumentDownload"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
