# coding: utf-8

"""
    UniCourt Enterprise APIs

    <button><a href=\"/developers/enterpriseapi/api/download/UniCourt-Enterprise-API-Spec.yaml\" >Download UniCourt Enterprise APIs Specification</a></button> 

    The version of the OpenAPI document: 
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from unicourt.models.case_count_analytics_by_jurisdiction_geo import CaseCountAnalyticsByJurisdictionGeo

class TestCaseCountAnalyticsByJurisdictionGeo(unittest.TestCase):
    """CaseCountAnalyticsByJurisdictionGeo unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> CaseCountAnalyticsByJurisdictionGeo:
        """Test CaseCountAnalyticsByJurisdictionGeo
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `CaseCountAnalyticsByJurisdictionGeo`
        """
        model = CaseCountAnalyticsByJurisdictionGeo()
        if include_optional:
            return CaseCountAnalyticsByJurisdictionGeo(
                object = 'CaseCountAnalyticsByJurisdictionGeo',
                case_count = 56,
                case_search_api = '',
                jurisdiction_geo = unicourt.models.jurisdiction_geo.JurisdictionGeo(
                    object = 'JurisdictionGeo', 
                    jurisdiction_geo_id = '01234567891011121314151617', 
                    country = '0', 
                    state = '0', 
                    county = '0', 
                    city = '0', 
                    fips_code = '0', 
                    zip_code_array = [
                        '0'
                        ], 
                    created_date = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                    courts_for_jurisdiction_geo_api = '0', ),
                geo = unicourt.models.case_count_analytics_by_court_geo.CaseCountAnalyticsByCourt_Geo(
                    latitude = '', 
                    longitude = '', )
            )
        else:
            return CaseCountAnalyticsByJurisdictionGeo(
                object = 'CaseCountAnalyticsByJurisdictionGeo',
                case_count = 56,
                case_search_api = '',
                jurisdiction_geo = unicourt.models.jurisdiction_geo.JurisdictionGeo(
                    object = 'JurisdictionGeo', 
                    jurisdiction_geo_id = '01234567891011121314151617', 
                    country = '0', 
                    state = '0', 
                    county = '0', 
                    city = '0', 
                    fips_code = '0', 
                    zip_code_array = [
                        '0'
                        ], 
                    created_date = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                    courts_for_jurisdiction_geo_api = '0', ),
                geo = unicourt.models.case_count_analytics_by_court_geo.CaseCountAnalyticsByCourt_Geo(
                    latitude = '', 
                    longitude = '', ),
        )
        """

    def testCaseCountAnalyticsByJurisdictionGeo(self):
        """Test CaseCountAnalyticsByJurisdictionGeo"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
