# coding: utf-8

"""
    UniCourt Enterprise APIs

    <button><a href=\"/developers/enterpriseapi/api/download/UniCourt-Enterprise-API-Spec.yaml\" >Download UniCourt Enterprise APIs Specification</a></button> 

    The version of the OpenAPI document: 
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from unicourt.api.case_tracking_api import CaseTrackingApi


class TestCaseTrackingApi(unittest.TestCase):
    """CaseTrackingApi unit test stubs"""

    def setUp(self) -> None:
        self.api = CaseTrackingApi()

    def tearDown(self) -> None:
        pass

    def test_get_case_track_by_id(self) -> None:
        """Test case for get_case_track_by_id

        Get Case Track for a requested Case Id.
        """
        pass

    def test_get_case_tracks(self) -> None:
        """Test case for get_case_tracks

        Get Case Track list.
        """
        pass

    def test_remove_case_track_by_id(self) -> None:
        """Test case for remove_case_track_by_id

        Remove Case Track for a specific Case Id.
        """
        pass

    def test_track_case(self) -> None:
        """Test case for track_case

        Add Case Track for the requested Case Id.
        """
        pass


if __name__ == '__main__':
    unittest.main()
