# coding: utf-8

"""
    UniCourt Enterprise APIs

    <button><a href=\"/developers/enterpriseapi/api/download/UniCourt-Enterprise-API-Spec.yaml\" >Download UniCourt Enterprise APIs Specification</a></button> 

    The version of the OpenAPI document: 
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from unicourt.models.party_attorney_association import PartyAttorneyAssociation

class TestPartyAttorneyAssociation(unittest.TestCase):
    """PartyAttorneyAssociation unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> PartyAttorneyAssociation:
        """Test PartyAttorneyAssociation
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `PartyAttorneyAssociation`
        """
        model = PartyAttorneyAssociation()
        if include_optional:
            return PartyAttorneyAssociation(
                object = 'PartyAttorneyAssociation',
                party_attorney_association_id = '01234567891011121314151617',
                attorney_id = '01234567891011121314151617',
                party_id = '01234567891011121314151617',
                is_visible = True
            )
        else:
            return PartyAttorneyAssociation(
                object = 'PartyAttorneyAssociation',
                party_attorney_association_id = '01234567891011121314151617',
                attorney_id = '01234567891011121314151617',
                party_id = '01234567891011121314151617',
                is_visible = True,
        )
        """

    def testPartyAttorneyAssociation(self):
        """Test PartyAttorneyAssociation"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
