# coding: utf-8

"""
    UniCourt Enterprise APIs

    <button><a href=\"/developers/enterpriseapi/api/download/UniCourt-Enterprise-API-Spec.yaml\" >Download UniCourt Enterprise APIs Specification</a></button> 

    The version of the OpenAPI document: 
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from unicourt.models.case_analytics_api import CaseAnalyticsAPI

class TestCaseAnalyticsAPI(unittest.TestCase):
    """CaseAnalyticsAPI unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> CaseAnalyticsAPI:
        """Test CaseAnalyticsAPI
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `CaseAnalyticsAPI`
        """
        model = CaseAnalyticsAPI()
        if include_optional:
            return CaseAnalyticsAPI(
                object = 'CaseAnalyticsAPI',
                case_count_analytics_by_court_api = '',
                case_count_analytics_by_court_type_api = '',
                case_count_analytics_by_court_system_api = '',
                case_count_analytics_by_court_location_api = '',
                case_count_analytics_by_jurisdiction_geo_api = '',
                case_count_analytics_by_area_of_law_api = '',
                case_count_analytics_by_case_class_api = '',
                case_count_analytics_by_case_type_api = '',
                case_count_analytics_by_case_type_group_api = '',
                case_count_analytics_by_party_role_api = '',
                case_count_analytics_by_party_role_group_api = '',
                total_cases = 56
            )
        else:
            return CaseAnalyticsAPI(
                object = 'CaseAnalyticsAPI',
                case_count_analytics_by_court_api = '',
                case_count_analytics_by_court_type_api = '',
                case_count_analytics_by_court_system_api = '',
                case_count_analytics_by_court_location_api = '',
                case_count_analytics_by_jurisdiction_geo_api = '',
                case_count_analytics_by_area_of_law_api = '',
                case_count_analytics_by_case_class_api = '',
                case_count_analytics_by_case_type_api = '',
                case_count_analytics_by_case_type_group_api = '',
                case_count_analytics_by_party_role_api = '',
                case_count_analytics_by_party_role_group_api = '',
                total_cases = 56,
        )
        """

    def testCaseAnalyticsAPI(self):
        """Test CaseAnalyticsAPI"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
