# coding: utf-8

"""
    UniCourt Enterprise APIs

    <button><a href=\"/developers/enterpriseapi/api/download/UniCourt-Enterprise-API-Spec.yaml\" >Download UniCourt Enterprise APIs Specification</a></button> 

    The version of the OpenAPI document: 
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from unicourt.models.norm_judge_public_data_bio import NormJudgePublicDataBio

class TestNormJudgePublicDataBio(unittest.TestCase):
    """NormJudgePublicDataBio unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> NormJudgePublicDataBio:
        """Test NormJudgePublicDataBio
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `NormJudgePublicDataBio`
        """
        model = NormJudgePublicDataBio()
        if include_optional:
            return NormJudgePublicDataBio(
                ethnicity = '',
                birth_city = '',
                birth_date = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
                birth_state = '',
                death_city = '',
                death_date = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
                death_state = '',
                political_affiliation = ''
            )
        else:
            return NormJudgePublicDataBio(
                ethnicity = '',
                birth_city = '',
                birth_date = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
                birth_state = '',
                death_city = '',
                death_date = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
                death_state = '',
                political_affiliation = '',
        )
        """

    def testNormJudgePublicDataBio(self):
        """Test NormJudgePublicDataBio"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
