# coding: utf-8

"""
    UniCourt Enterprise APIs

    <button><a href=\"/developers/enterpriseapi/api/download/UniCourt-Enterprise-API-Spec.yaml\" >Download UniCourt Enterprise APIs Specification</a></button> 

    The version of the OpenAPI document: 
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from unicourt.models.court_system_response import CourtSystemResponse

class TestCourtSystemResponse(unittest.TestCase):
    """CourtSystemResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> CourtSystemResponse:
        """Test CourtSystemResponse
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `CourtSystemResponse`
        """
        model = CourtSystemResponse()
        if include_optional:
            return CourtSystemResponse(
                object = 'CourtSystemResponse',
                court_system_array = [
                    unicourt.models.court_system.CourtSystem(
                        object = 'CourtSystem', 
                        court_type_id = '01234567891011121314151617', 
                        court_system_id = '01234567891011121314151617', 
                        court_type = '0', 
                        name = '0', 
                        created_date = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), )
                    ],
                next_page_api = '0',
                previous_page_api = '0',
                page_number = 1,
                total_pages = 1,
                total_count = 1
            )
        else:
            return CourtSystemResponse(
                object = 'CourtSystemResponse',
                court_system_array = [
                    unicourt.models.court_system.CourtSystem(
                        object = 'CourtSystem', 
                        court_type_id = '01234567891011121314151617', 
                        court_system_id = '01234567891011121314151617', 
                        court_type = '0', 
                        name = '0', 
                        created_date = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), )
                    ],
                next_page_api = '0',
                previous_page_api = '0',
                page_number = 1,
                total_pages = 1,
                total_count = 1,
        )
        """

    def testCourtSystemResponse(self):
        """Test CourtSystemResponse"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
