# coding: utf-8

"""
    UniCourt Enterprise APIs

    <button><a href=\"/developers/enterpriseapi/api/download/UniCourt-Enterprise-API-Spec.yaml\" >Download UniCourt Enterprise APIs Specification</a></button> 

    The version of the OpenAPI document: 
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from unicourt.models.hearing import Hearing

class TestHearing(unittest.TestCase):
    """Hearing unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> Hearing:
        """Test Hearing
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `Hearing`
        """
        model = Hearing()
        if include_optional:
            return Hearing(
                object = 'Hearing',
                hearing_date = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
                hearing_description = '',
                hearing_structured = unicourt.models.source_structured_data.SourceStructuredData(
                    raw_ordered_data_array = [
                        unicourt.models.raw_ordered_data.RawOrderedData(
                            child_array = [
                                unicourt.models.raw_ordered_data_child.RawOrderedDataChild(
                                    child_array = [
                                        unicourt.models.raw_ordered_data_child_child_array_inner.RawOrderedDataChild_childArray_inner(
                                            lbl = '', 
                                            ord = 56, 
                                            val = '', 
                                            child_array = [
                                                None
                                                ], )
                                        ], 
                                    lbl = '', 
                                    ord = 56, 
                                    val = '', )
                                ], 
                            lbl = '', 
                            ord = 56, 
                            val = '', )
                        ], 
                    extracted_fields = { }, ),
                location = '',
                first_fetch_date = '0123456789101112131415161718192021222324',
                last_fetch_date = '0123456789101112131415161718192021222324'
            )
        else:
            return Hearing(
                object = 'Hearing',
                hearing_date = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
                hearing_description = '',
                hearing_structured = unicourt.models.source_structured_data.SourceStructuredData(
                    raw_ordered_data_array = [
                        unicourt.models.raw_ordered_data.RawOrderedData(
                            child_array = [
                                unicourt.models.raw_ordered_data_child.RawOrderedDataChild(
                                    child_array = [
                                        unicourt.models.raw_ordered_data_child_child_array_inner.RawOrderedDataChild_childArray_inner(
                                            lbl = '', 
                                            ord = 56, 
                                            val = '', 
                                            child_array = [
                                                None
                                                ], )
                                        ], 
                                    lbl = '', 
                                    ord = 56, 
                                    val = '', )
                                ], 
                            lbl = '', 
                            ord = 56, 
                            val = '', )
                        ], 
                    extracted_fields = { }, ),
                location = '',
                first_fetch_date = '0123456789101112131415161718192021222324',
                last_fetch_date = '0123456789101112131415161718192021222324',
        )
        """

    def testHearing(self):
        """Test Hearing"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
