# coding: utf-8

"""
    UniCourt Enterprise APIs

    <button><a href=\"/developers/enterpriseapi/api/download/UniCourt-Enterprise-API-Spec.yaml\" >Download UniCourt Enterprise APIs Specification</a></button> 

    The version of the OpenAPI document: 
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from unicourt.models.case_document_order_callback_list_response import CaseDocumentOrderCallbackListResponse

class TestCaseDocumentOrderCallbackListResponse(unittest.TestCase):
    """CaseDocumentOrderCallbackListResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> CaseDocumentOrderCallbackListResponse:
        """Test CaseDocumentOrderCallbackListResponse
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `CaseDocumentOrderCallbackListResponse`
        """
        model = CaseDocumentOrderCallbackListResponse()
        if include_optional:
            return CaseDocumentOrderCallbackListResponse(
                object = 'CaseDocumentOrderCallbackListResponse',
                total_pages = 56,
                total_count = 56,
                page_number = 56,
                next_page_api = '0',
                previous_page_api = '0',
                callback_array = [
                    unicourt.models.case_document_order_callback.CaseDocumentOrderCallback(
                        object = 'CaseDocumentOrderCallback', 
                        case_document_order_callback_id = '01234567891011121314151617', 
                        case_document_id = '01234567891011121314151617', 
                        callback_generated_date = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                        status = 'COMPLETE', 
                        case_document = unicourt.models.case_document.CaseDocument(
                            object = 'CaseDocument', 
                            case_document_id = '01234567891011121314151617', 
                            sort_order = 56, 
                            name = '', 
                            description = '', 
                            document_filed_date = '0123456789101112131415161718192021222324', 
                            parent_document_id = '01234567891011121314151617', 
                            child_document_id_array = [
                                '01234567891011121314151617'
                                ], 
                            pages = 56, 
                            is_preview_available = True, 
                            preview_document = unicourt.models.preview_document.PreviewDocument(
                                object = 'PreviewDocument', 
                                in_library = True, 
                                added_to_library_date = '0123456789101112131415161718192021222324', 
                                download_api = '', ), 
                            price = 1.337, 
                            in_library = True, 
                            added_to_library_date = '0123456789101112131415161718192021222324', 
                            estimated_order_duration = 'estimateUnavailable', 
                            download_api = '', 
                            first_fetch_date = '0123456789101112131415161718192021222324', 
                            source_data_status = 'NO_LONGER_AVAILABLE_IN_COURT', ), 
                        case_document_order_callback_api = '0', 
                        file = unicourt.models.export_file.ExportFile(
                            object = 'ExportFile', 
                            name = '0', 
                            expiry_date = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                            file_url = '0', ), 
                        exception = unicourt.models.exception.Exception(
                            object = 'Exception', 
                            code = '0', 
                            message = '0', 
                            details = '0', ), )
                    ]
            )
        else:
            return CaseDocumentOrderCallbackListResponse(
                object = 'CaseDocumentOrderCallbackListResponse',
                total_pages = 56,
                total_count = 56,
                page_number = 56,
                next_page_api = '0',
                previous_page_api = '0',
                callback_array = [
                    unicourt.models.case_document_order_callback.CaseDocumentOrderCallback(
                        object = 'CaseDocumentOrderCallback', 
                        case_document_order_callback_id = '01234567891011121314151617', 
                        case_document_id = '01234567891011121314151617', 
                        callback_generated_date = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                        status = 'COMPLETE', 
                        case_document = unicourt.models.case_document.CaseDocument(
                            object = 'CaseDocument', 
                            case_document_id = '01234567891011121314151617', 
                            sort_order = 56, 
                            name = '', 
                            description = '', 
                            document_filed_date = '0123456789101112131415161718192021222324', 
                            parent_document_id = '01234567891011121314151617', 
                            child_document_id_array = [
                                '01234567891011121314151617'
                                ], 
                            pages = 56, 
                            is_preview_available = True, 
                            preview_document = unicourt.models.preview_document.PreviewDocument(
                                object = 'PreviewDocument', 
                                in_library = True, 
                                added_to_library_date = '0123456789101112131415161718192021222324', 
                                download_api = '', ), 
                            price = 1.337, 
                            in_library = True, 
                            added_to_library_date = '0123456789101112131415161718192021222324', 
                            estimated_order_duration = 'estimateUnavailable', 
                            download_api = '', 
                            first_fetch_date = '0123456789101112131415161718192021222324', 
                            source_data_status = 'NO_LONGER_AVAILABLE_IN_COURT', ), 
                        case_document_order_callback_api = '0', 
                        file = unicourt.models.export_file.ExportFile(
                            object = 'ExportFile', 
                            name = '0', 
                            expiry_date = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                            file_url = '0', ), 
                        exception = unicourt.models.exception.Exception(
                            object = 'Exception', 
                            code = '0', 
                            message = '0', 
                            details = '0', ), )
                    ],
        )
        """

    def testCaseDocumentOrderCallbackListResponse(self):
        """Test CaseDocumentOrderCallbackListResponse"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
