# coding: utf-8

"""
    UniCourt Enterprise APIs

    <button><a href=\"/developers/enterpriseapi/api/download/UniCourt-Enterprise-API-Spec.yaml\" >Download UniCourt Enterprise APIs Specification</a></button> 

    The version of the OpenAPI document: 
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from unicourt.api.case_docket_api import CaseDocketApi


class TestCaseDocketApi(unittest.TestCase):
    """CaseDocketApi unit test stubs"""

    def setUp(self) -> None:
        self.api = CaseDocketApi()

    def tearDown(self) -> None:
        pass

    def test_get_attorney_associated_parties(self) -> None:
        """Test case for get_attorney_associated_parties

        Gets Associated Party details for a requested Attorney ID.
        """
        pass

    def test_get_attorney_by_id(self) -> None:
        """Test case for get_attorney_by_id

        Gets details for a requested Attorney ID.
        """
        pass

    def test_get_case(self) -> None:
        """Test case for get_case

        Gets case information for a requested Case ID.
        """
        pass

    def test_get_case_attorneys(self) -> None:
        """Test case for get_case_attorneys

        Gets Attorneys for a requested Case ID.
        """
        pass

    def test_get_case_docket_entries(self) -> None:
        """Test case for get_case_docket_entries

        Gets Docket Entries for a requested Case ID.
        """
        pass

    def test_get_case_hearings(self) -> None:
        """Test case for get_case_hearings

        Gets Hearings for a requested Case ID.
        """
        pass

    def test_get_case_judges(self) -> None:
        """Test case for get_case_judges

        Gets Judges for a requested Case ID.
        """
        pass

    def test_get_case_parties(self) -> None:
        """Test case for get_case_parties

        Gets Parties for a requested Case ID.
        """
        pass

    def test_get_case_related_cases(self) -> None:
        """Test case for get_case_related_cases

        Gets Related Cases for a requested Case ID.
        """
        pass

    def test_get_judge_by_id(self) -> None:
        """Test case for get_judge_by_id

        Gets details for a requested Judge ID.
        """
        pass

    def test_get_party_associated_attorneys(self) -> None:
        """Test case for get_party_associated_attorneys

        Gets Associated Attorney details for a requested Party ID.
        """
        pass

    def test_get_party_by_id(self) -> None:
        """Test case for get_party_by_id

        Gets details for a requested Party ID.
        """
        pass

    def test_get_primary_documents_for_docket_entries(self) -> None:
        """Test case for get_primary_documents_for_docket_entries

        Gets Primary Documents of Docket Entries.
        """
        pass

    def test_get_secondary_documents_for_docket_entries(self) -> None:
        """Test case for get_secondary_documents_for_docket_entries

        Gets Secondary Documents of Docket Entries.
        """
        pass


if __name__ == '__main__':
    unittest.main()
