# coding: utf-8

"""
    UniCourt Enterprise APIs

    <button><a href=\"/developers/enterpriseapi/api/download/UniCourt-Enterprise-API-Spec.yaml\" >Download UniCourt Enterprise APIs Specification</a></button> 

    The version of the OpenAPI document: 
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from unicourt.models.possible_norm_judge_score_constituents import PossibleNormJudgeScoreConstituents

class TestPossibleNormJudgeScoreConstituents(unittest.TestCase):
    """PossibleNormJudgeScoreConstituents unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> PossibleNormJudgeScoreConstituents:
        """Test PossibleNormJudgeScoreConstituents
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `PossibleNormJudgeScoreConstituents`
        """
        model = PossibleNormJudgeScoreConstituents()
        if include_optional:
            return PossibleNormJudgeScoreConstituents(
                name_similarity_score = 1.337,
                other_potential_norm_judges = 56,
                address = 'Matched',
                email = 'Matched',
                phone = 'Matched'
            )
        else:
            return PossibleNormJudgeScoreConstituents(
                name_similarity_score = 1.337,
                other_potential_norm_judges = 56,
                address = 'Matched',
                email = 'Matched',
                phone = 'Matched',
        )
        """

    def testPossibleNormJudgeScoreConstituents(self):
        """Test PossibleNormJudgeScoreConstituents"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
