# coding: utf-8

"""
    UniCourt Enterprise APIs

    <button><a href=\"/developers/enterpriseapi/api/download/UniCourt-Enterprise-API-Spec.yaml\" >Download UniCourt Enterprise APIs Specification</a></button> 

    The version of the OpenAPI document: 
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from unicourt.models.court_location import CourtLocation

class TestCourtLocation(unittest.TestCase):
    """CourtLocation unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> CourtLocation:
        """Test CourtLocation
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `CourtLocation`
        """
        model = CourtLocation()
        if include_optional:
            return CourtLocation(
                object = 'CourtLocation',
                court_location_id = '01234567891011121314151617',
                name = '0',
                street_address1 = '0',
                street_address2 = '',
                city = '',
                state_name = 'UNKNOWN',
                created_date = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
                courts_for_court_location_api = '0',
                court_service_status_api = '0'
            )
        else:
            return CourtLocation(
                object = 'CourtLocation',
                court_location_id = '01234567891011121314151617',
                name = '0',
                street_address1 = '0',
                street_address2 = '',
                city = '',
                state_name = 'UNKNOWN',
                created_date = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
                courts_for_court_location_api = '0',
                court_service_status_api = '0',
        )
        """

    def testCourtLocation(self):
        """Test CourtLocation"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
