# coding: utf-8

"""
    UniCourt Enterprise APIs

    <button><a href=\"/developers/enterpriseapi/api/download/UniCourt-Enterprise-API-Spec.yaml\" >Download UniCourt Enterprise APIs Specification</a></button> 

    The version of the OpenAPI document: 
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from unicourt.models.sos_data_preview import SOSDataPreview

class TestSOSDataPreview(unittest.TestCase):
    """SOSDataPreview unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> SOSDataPreview:
        """Test SOSDataPreview
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `SOSDataPreview`
        """
        model = SOSDataPreview()
        if include_optional:
            return SOSDataPreview(
                object = 'SOSDataPreview',
                sos_number = '',
                state_code = ''
            )
        else:
            return SOSDataPreview(
                object = 'SOSDataPreview',
                sos_number = '',
                state_code = '',
        )
        """

    def testSOSDataPreview(self):
        """Test SOSDataPreview"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
