# coding: utf-8

"""
    UniCourt Enterprise APIs

    <button><a href=\"/developers/enterpriseapi/api/download/UniCourt-Enterprise-API-Spec.yaml\" >Download UniCourt Enterprise APIs Specification</a></button> 

    The version of the OpenAPI document: 
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from unicourt.models.related_cases import RelatedCases

class TestRelatedCases(unittest.TestCase):
    """RelatedCases unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> RelatedCases:
        """Test RelatedCases
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `RelatedCases`
        """
        model = RelatedCases()
        if include_optional:
            return RelatedCases(
                object = 'RelatedCases',
                page_number = 56,
                related_case_array = [
                    unicourt.models.related_case.RelatedCase(
                        object = 'RelatedCase', 
                        case_id = '01234567891011121314151617', 
                        case_number = '012', 
                        case_name = '', 
                        case_relationship_type = unicourt.models.case_relationship_type.CaseRelationshipType(
                            object = 'CaseRelationshipType', 
                            case_relationship_type_id = '01234567891011121314151617', 
                            name = '0', 
                            created_date = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), ), 
                        source_case_relationship_type = '012', 
                        is_visible = True, 
                        additional_source_data = unicourt.models.source_structured_data.SourceStructuredData(
                            raw_ordered_data_array = [
                                unicourt.models.raw_ordered_data.RawOrderedData(
                                    child_array = [
                                        unicourt.models.raw_ordered_data_child.RawOrderedDataChild(
                                            child_array = [
                                                unicourt.models.raw_ordered_data_child_child_array_inner.RawOrderedDataChild_childArray_inner(
                                                    lbl = '', 
                                                    ord = 56, 
                                                    val = '', 
                                                    child_array = [
                                                        None
                                                        ], )
                                                ], 
                                            lbl = '', 
                                            ord = 56, 
                                            val = '', )
                                        ], 
                                    lbl = '', 
                                    ord = 56, 
                                    val = '', )
                                ], 
                            extracted_fields = { }, ), 
                        case_api = '', )
                    ],
                next_page_api = '',
                total_pages = 56,
                total_count = 56
            )
        else:
            return RelatedCases(
                object = 'RelatedCases',
                page_number = 56,
                related_case_array = [
                    unicourt.models.related_case.RelatedCase(
                        object = 'RelatedCase', 
                        case_id = '01234567891011121314151617', 
                        case_number = '012', 
                        case_name = '', 
                        case_relationship_type = unicourt.models.case_relationship_type.CaseRelationshipType(
                            object = 'CaseRelationshipType', 
                            case_relationship_type_id = '01234567891011121314151617', 
                            name = '0', 
                            created_date = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), ), 
                        source_case_relationship_type = '012', 
                        is_visible = True, 
                        additional_source_data = unicourt.models.source_structured_data.SourceStructuredData(
                            raw_ordered_data_array = [
                                unicourt.models.raw_ordered_data.RawOrderedData(
                                    child_array = [
                                        unicourt.models.raw_ordered_data_child.RawOrderedDataChild(
                                            child_array = [
                                                unicourt.models.raw_ordered_data_child_child_array_inner.RawOrderedDataChild_childArray_inner(
                                                    lbl = '', 
                                                    ord = 56, 
                                                    val = '', 
                                                    child_array = [
                                                        None
                                                        ], )
                                                ], 
                                            lbl = '', 
                                            ord = 56, 
                                            val = '', )
                                        ], 
                                    lbl = '', 
                                    ord = 56, 
                                    val = '', )
                                ], 
                            extracted_fields = { }, ), 
                        case_api = '', )
                    ],
                next_page_api = '',
                total_pages = 56,
                total_count = 56,
        )
        """

    def testRelatedCases(self):
        """Test RelatedCases"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
