# coding: utf-8

"""
    UniCourt Enterprise APIs

    <button><a href=\"/developers/enterpriseapi/api/download/UniCourt-Enterprise-API-Spec.yaml\" >Download UniCourt Enterprise APIs Specification</a></button> 

    The version of the OpenAPI document: 
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from unicourt.api.court_availability_api import CourtAvailabilityApi


class TestCourtAvailabilityApi(unittest.TestCase):
    """CourtAvailabilityApi unit test stubs"""

    def setUp(self) -> None:
        self.api = CourtAvailabilityApi()

    def tearDown(self) -> None:
        pass

    def test_get_court_coverage(self) -> None:
        """Test case for get_court_coverage

        Gets Court Coverage of all courts of specific type.
        """
        pass


if __name__ == '__main__':
    unittest.main()
