# coding: utf-8

"""
    UniCourt Enterprise APIs

    <button><a href=\"/developers/enterpriseapi/api/download/UniCourt-Enterprise-API-Spec.yaml\" >Download UniCourt Enterprise APIs Specification</a></button> 

    The version of the OpenAPI document: 
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from unicourt.api.pacer_credential_api import PACERCredentialApi


class TestPACERCredentialApi(unittest.TestCase):
    """PACERCredentialApi unit test stubs"""

    def setUp(self) -> None:
        self.api = PACERCredentialApi()

    def tearDown(self) -> None:
        pass

    def test_add_pacer_credential(self) -> None:
        """Test case for add_pacer_credential

        Add Pacer Credential.
        """
        pass

    def test_get_pacer_credential(self) -> None:
        """Test case for get_pacer_credential

        Get Pacer Credential List.
        """
        pass

    def test_get_pacer_credential_by_id(self) -> None:
        """Test case for get_pacer_credential_by_id

        Get Pacer Credential for a requested pacer User Id.
        """
        pass

    def test_remove_pacer_credential_by_id(self) -> None:
        """Test case for remove_pacer_credential_by_id

        Remove Pacer credential for a specific Pacer User Id.
        """
        pass


if __name__ == '__main__':
    unittest.main()
