# coding: utf-8

"""
    UniCourt Enterprise APIs

    <button><a href=\"/developers/enterpriseapi/api/download/UniCourt-Enterprise-API-Spec.yaml\" >Download UniCourt Enterprise APIs Specification</a></button> 

    The version of the OpenAPI document: 
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from unicourt.api.authentication_api import AuthenticationApi


class TestAuthenticationApi(unittest.TestCase):
    """AuthenticationApi unit test stubs"""

    def setUp(self) -> None:
        self.api = AuthenticationApi()

    def tearDown(self) -> None:
        pass

    def test_generate_new_token(self) -> None:
        """Test case for generate_new_token

        Generate new token to access API.
        """
        pass

    def test_invalidate_all_tokens(self) -> None:
        """Test case for invalidate_all_tokens

        API to invalidate all access tokens.
        """
        pass

    def test_invalidate_token(self) -> None:
        """Test case for invalidate_token

        API to invalidate the access token.
        """
        pass

    def test_list_all_token_ids(self) -> None:
        """Test case for list_all_token_ids

        API to list all the access tokens Id.
        """
        pass


if __name__ == '__main__':
    unittest.main()
