# coding: utf-8

"""
    UniCourt Enterprise APIs

    <button><a href=\"/developers/enterpriseapi/api/download/UniCourt-Enterprise-API-Spec.yaml\" >Download UniCourt Enterprise APIs Specification</a></button> 

    The version of the OpenAPI document: 
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from unicourt.models.case_class_response import CaseClassResponse

class TestCaseClassResponse(unittest.TestCase):
    """CaseClassResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> CaseClassResponse:
        """Test CaseClassResponse
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `CaseClassResponse`
        """
        model = CaseClassResponse()
        if include_optional:
            return CaseClassResponse(
                object = 'CaseClassResponse',
                case_class_array = [
                    unicourt.models.case_class.CaseClass(
                        object = 'CaseClass', 
                        case_class_id = '01234567891011121314151617', 
                        name = '0', 
                        created_date = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), )
                    ],
                next_page_api = '0',
                previous_page_api = '0',
                page_number = 1,
                total_pages = 1,
                total_count = 1
            )
        else:
            return CaseClassResponse(
                object = 'CaseClassResponse',
                case_class_array = [
                    unicourt.models.case_class.CaseClass(
                        object = 'CaseClass', 
                        case_class_id = '01234567891011121314151617', 
                        name = '0', 
                        created_date = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), )
                    ],
                next_page_api = '0',
                previous_page_api = '0',
                page_number = 1,
                total_pages = 1,
                total_count = 1,
        )
        """

    def testCaseClassResponse(self):
        """Test CaseClassResponse"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
