# coding: utf-8

"""
    UniCourt Enterprise APIs

    <button><a href=\"/developers/enterpriseapi/api/download/UniCourt-Enterprise-API-Spec.yaml\" >Download UniCourt Enterprise APIs Specification</a></button> 

    The version of the OpenAPI document: 
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from unicourt.api.callback_api import CallbackApi


class TestCallbackApi(unittest.TestCase):
    """CallbackApi unit test stubs"""

    def setUp(self) -> None:
        self.api = CallbackApi()

    def tearDown(self) -> None:
        pass

    def test_get_callbacks(self) -> None:
        """Test case for get_callbacks

        Get list of callback types with count for a requested Date.
        """
        pass


if __name__ == '__main__':
    unittest.main()
