# coding: utf-8

"""
    UniCourt Enterprise APIs

    <button><a href=\"/developers/enterpriseapi/api/download/UniCourt-Enterprise-API-Spec.yaml\" >Download UniCourt Enterprise APIs Specification</a></button> 

    The version of the OpenAPI document: 
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from unicourt.models.possible_norm_attorney_score_constituents import PossibleNormAttorneyScoreConstituents

class TestPossibleNormAttorneyScoreConstituents(unittest.TestCase):
    """PossibleNormAttorneyScoreConstituents unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> PossibleNormAttorneyScoreConstituents:
        """Test PossibleNormAttorneyScoreConstituents
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `PossibleNormAttorneyScoreConstituents`
        """
        model = PossibleNormAttorneyScoreConstituents()
        if include_optional:
            return PossibleNormAttorneyScoreConstituents(
                name_similarity_score = 1.337,
                other_potential_norm_attorneys = 56,
                bar_id = 'Matched',
                address = 'Matched',
                email = 'Matched',
                phone = 'Matched',
                law_firm = 'Matched'
            )
        else:
            return PossibleNormAttorneyScoreConstituents(
                name_similarity_score = 1.337,
                other_potential_norm_attorneys = 56,
                bar_id = 'Matched',
                address = 'Matched',
                email = 'Matched',
                phone = 'Matched',
                law_firm = 'Matched',
        )
        """

    def testPossibleNormAttorneyScoreConstituents(self):
        """Test PossibleNormAttorneyScoreConstituents"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
