# coding: utf-8

"""
    UniCourt Enterprise APIs

    <button><a href=\"/developers/enterpriseapi/api/download/UniCourt-Enterprise-API-Spec.yaml\" >Download UniCourt Enterprise APIs Specification</a></button> 

    The version of the OpenAPI document: 
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from unicourt.models.possible_norm_party import PossibleNormParty

class TestPossibleNormParty(unittest.TestCase):
    """PossibleNormParty unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> PossibleNormParty:
        """Test PossibleNormParty
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `PossibleNormParty`
        """
        model = PossibleNormParty()
        if include_optional:
            return PossibleNormParty(
                object = 'PossibleNormParty',
                norm_party_id = '01234567891011121314151617',
                norm_party_name = '',
                best_match = True,
                confidence_score = 1.337,
                score_constituents = unicourt.models.possible_norm_party_score_constituents.PossibleNormParty_scoreConstituents(
                    name_similarity_score = 1.337, 
                    other_potential_norm_parties = 56, 
                    secretary_of_state_id = 'Matched', 
                    address = 'Matched', 
                    email = 'Matched', 
                    phone = 'Matched', ),
                norm_party_api = '',
                associated_norm_attorneys_api = '',
                associated_norm_law_firms_api = '',
                associated_norm_judges_api = '',
                case_count_analytics_by_norm_party_api = '',
                case_count_analytics_by_opposing_norm_party_api = ''
            )
        else:
            return PossibleNormParty(
                object = 'PossibleNormParty',
                norm_party_id = '01234567891011121314151617',
                norm_party_name = '',
                best_match = True,
                confidence_score = 1.337,
                score_constituents = unicourt.models.possible_norm_party_score_constituents.PossibleNormParty_scoreConstituents(
                    name_similarity_score = 1.337, 
                    other_potential_norm_parties = 56, 
                    secretary_of_state_id = 'Matched', 
                    address = 'Matched', 
                    email = 'Matched', 
                    phone = 'Matched', ),
                norm_party_api = '',
                associated_norm_attorneys_api = '',
                associated_norm_law_firms_api = '',
                associated_norm_judges_api = '',
                case_count_analytics_by_norm_party_api = '',
                case_count_analytics_by_opposing_norm_party_api = '',
        )
        """

    def testPossibleNormParty(self):
        """Test PossibleNormParty"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
