# coding: utf-8

"""
    UniCourt Enterprise APIs

    <button><a href=\"/developers/enterpriseapi/api/download/UniCourt-Enterprise-API-Spec.yaml\" >Download UniCourt Enterprise APIs Specification</a></button> 

    The version of the OpenAPI document: 
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from unicourt.models.case_count_analytics_by_court_system import CaseCountAnalyticsByCourtSystem

class TestCaseCountAnalyticsByCourtSystem(unittest.TestCase):
    """CaseCountAnalyticsByCourtSystem unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> CaseCountAnalyticsByCourtSystem:
        """Test CaseCountAnalyticsByCourtSystem
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `CaseCountAnalyticsByCourtSystem`
        """
        model = CaseCountAnalyticsByCourtSystem()
        if include_optional:
            return CaseCountAnalyticsByCourtSystem(
                object = 'CaseCountAnalyticsByCourtSystem',
                case_count = 56,
                case_search_api = '',
                court_system = unicourt.models.court_system.CourtSystem(
                    object = 'CourtSystem', 
                    court_type_id = '01234567891011121314151617', 
                    court_system_id = '01234567891011121314151617', 
                    court_type = '0', 
                    name = '0', 
                    created_date = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), ),
                geo = unicourt.models.case_count_analytics_by_court_geo.CaseCountAnalyticsByCourt_Geo(
                    latitude = '', 
                    longitude = '', )
            )
        else:
            return CaseCountAnalyticsByCourtSystem(
                object = 'CaseCountAnalyticsByCourtSystem',
                case_count = 56,
                case_search_api = '',
                court_system = unicourt.models.court_system.CourtSystem(
                    object = 'CourtSystem', 
                    court_type_id = '01234567891011121314151617', 
                    court_system_id = '01234567891011121314151617', 
                    court_type = '0', 
                    name = '0', 
                    created_date = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), ),
                geo = unicourt.models.case_count_analytics_by_court_geo.CaseCountAnalyticsByCourt_Geo(
                    latitude = '', 
                    longitude = '', ),
        )
        """

    def testCaseCountAnalyticsByCourtSystem(self):
        """Test CaseCountAnalyticsByCourtSystem"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
