# coding: utf-8

"""
    UniCourt Enterprise APIs

    <button><a href=\"/developers/enterpriseapi/api/download/UniCourt-Enterprise-API-Spec.yaml\" >Download UniCourt Enterprise APIs Specification</a></button> 

    The version of the OpenAPI document: 
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from unicourt.api.pacer_api import PACERApi


class TestPACERApi(unittest.TestCase):
    """PACERApi unit test stubs"""

    def setUp(self) -> None:
        self.api = PACERApi()

    def tearDown(self) -> None:
        pass

    def test_all_courts_pacer_case_locator_case_search(self) -> None:
        """Test case for all_courts_pacer_case_locator_case_search

        PACER Case Locator Search API for All Courts.
        """
        pass

    def test_all_courts_pacer_case_locator_party_search(self) -> None:
        """Test case for all_courts_pacer_case_locator_party_search

        PACER Case Locator Search API for All Courts.
        """
        pass

    def test_appeal_courts_pacer_case_locator_case_search(self) -> None:
        """Test case for appeal_courts_pacer_case_locator_case_search

        PACER Case Locator Search API for All Courts.
        """
        pass

    def test_appeal_courts_pacer_case_locator_party_search(self) -> None:
        """Test case for appeal_courts_pacer_case_locator_party_search

        PACER Case Locator Search API for All Courts.
        """
        pass

    def test_bankruptcy_courts_pacer_case_locator_case_search(self) -> None:
        """Test case for bankruptcy_courts_pacer_case_locator_case_search

        PACER Case Locator Search API for Bankruptcy Courts.
        """
        pass

    def test_bankruptcy_courts_pacer_case_locator_party_search(self) -> None:
        """Test case for bankruptcy_courts_pacer_case_locator_party_search

        PACER Case Locator Search API for All Courts.
        """
        pass

    def test_civil_courts_pacer_case_locator_case_search(self) -> None:
        """Test case for civil_courts_pacer_case_locator_case_search

        PACER Case Locator Search API for All Courts.
        """
        pass

    def test_civil_courts_pacer_case_locator_party_search(self) -> None:
        """Test case for civil_courts_pacer_case_locator_party_search

        PACER Case Locator Search API for All Courts.
        """
        pass

    def test_criminal_courts_pacer_case_locator_case_search(self) -> None:
        """Test case for criminal_courts_pacer_case_locator_case_search

        PACER Case Locator Search API for All Courts.
        """
        pass

    def test_criminal_courts_pacer_case_locator_party_search(self) -> None:
        """Test case for criminal_courts_pacer_case_locator_party_search

        PACER Case Locator Search API for All Courts.
        """
        pass

    def test_import_pacer_case_by_court_using_case_number(self) -> None:
        """Test case for import_pacer_case_by_court_using_case_number

        Find PACER Case for a requested Case Number and Court.
        """
        pass

    def test_multi_district_courts_pacer_case_locator_case_search(self) -> None:
        """Test case for multi_district_courts_pacer_case_locator_case_search

        PACER Case Locator Search API for All Courts.
        """
        pass

    def test_multi_district_courts_pacer_case_locator_party_search(self) -> None:
        """Test case for multi_district_courts_pacer_case_locator_party_search

        PACER Case Locator Search API for All Courts.
        """
        pass


if __name__ == '__main__':
    unittest.main()
