# coding: utf-8

"""
    UniCourt Enterprise APIs

    <button><a href=\"/developers/enterpriseapi/api/download/UniCourt-Enterprise-API-Spec.yaml\" >Download UniCourt Enterprise APIs Specification</a></button> 

    The version of the OpenAPI document: 
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from unicourt.models.raw_ordered_data_child import RawOrderedDataChild

class TestRawOrderedDataChild(unittest.TestCase):
    """RawOrderedDataChild unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> RawOrderedDataChild:
        """Test RawOrderedDataChild
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `RawOrderedDataChild`
        """
        model = RawOrderedDataChild()
        if include_optional:
            return RawOrderedDataChild(
                child_array = [
                    unicourt.models.raw_ordered_data_child_child_array_inner.RawOrderedDataChild_childArray_inner(
                        lbl = '', 
                        ord = 56, 
                        val = '', 
                        child_array = [
                            None
                            ], )
                    ],
                lbl = '',
                ord = 56,
                val = ''
            )
        else:
            return RawOrderedDataChild(
                child_array = [
                    unicourt.models.raw_ordered_data_child_child_array_inner.RawOrderedDataChild_childArray_inner(
                        lbl = '', 
                        ord = 56, 
                        val = '', 
                        child_array = [
                            None
                            ], )
                    ],
                lbl = '',
                ord = 56,
                val = '',
        )
        """

    def testRawOrderedDataChild(self):
        """Test RawOrderedDataChild"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
