# coding: utf-8

"""
    UniCourt Enterprise APIs

    <button><a href=\"/developers/enterpriseapi/api/download/UniCourt-Enterprise-API-Spec.yaml\" >Download UniCourt Enterprise APIs Specification</a></button> 

    The version of the OpenAPI document: 
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from unicourt.models.service_history import ServiceHistory

class TestServiceHistory(unittest.TestCase):
    """ServiceHistory unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ServiceHistory:
        """Test ServiceHistory
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ServiceHistory`
        """
        model = ServiceHistory()
        if include_optional:
            return ServiceHistory(
                object = 'ServiceHistory',
                appointed_by = '',
                reason_for_termination = '',
                source_court = '',
                title = '',
                from_year = 56,
                to_year = 56,
                from_date = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
                to_date = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
                is_visible = True
            )
        else:
            return ServiceHistory(
                object = 'ServiceHistory',
                appointed_by = '',
                reason_for_termination = '',
                source_court = '',
                title = '',
                from_year = 56,
                to_year = 56,
                from_date = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
                to_date = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
                is_visible = True,
        )
        """

    def testServiceHistory(self):
        """Test ServiceHistory"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
