# coding: utf-8

"""
    UniCourt Enterprise APIs

    <button><a href=\"/developers/enterpriseapi/api/download/UniCourt-Enterprise-API-Spec.yaml\" >Download UniCourt Enterprise APIs Specification</a></button> 

    The version of the OpenAPI document: 
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from unicourt.models.daily_usage_response import DailyUsageResponse

class TestDailyUsageResponse(unittest.TestCase):
    """DailyUsageResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> DailyUsageResponse:
        """Test DailyUsageResponse
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `DailyUsageResponse`
        """
        model = DailyUsageResponse()
        if include_optional:
            return DailyUsageResponse(
                object = 'DailyUsageResponse',
                usage_start_time = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
                usage_end_time = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
                api_usage = None,
                api_calls_made = unicourt.models.billing_cycle_usage_response_api_calls_made.BillingCycleUsageResponse_apiCallsMade(
                    count = 56, 
                    last_updated = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), ),
                api_calls_credited = unicourt.models.billing_cycle_usage_response_api_calls_credited.BillingCycleUsageResponse_apiCallsCredited(
                    count = 56, 
                    last_updated = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), ),
                api_calls_billable = unicourt.models.billing_cycle_usage_response_api_calls_billable.BillingCycleUsageResponse_apiCallsBillable(
                    count = 56, 
                    last_updated = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), )
            )
        else:
            return DailyUsageResponse(
                object = 'DailyUsageResponse',
                usage_start_time = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
                usage_end_time = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
                api_usage = None,
                api_calls_made = unicourt.models.billing_cycle_usage_response_api_calls_made.BillingCycleUsageResponse_apiCallsMade(
                    count = 56, 
                    last_updated = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), ),
                api_calls_credited = unicourt.models.billing_cycle_usage_response_api_calls_credited.BillingCycleUsageResponse_apiCallsCredited(
                    count = 56, 
                    last_updated = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), ),
                api_calls_billable = unicourt.models.billing_cycle_usage_response_api_calls_billable.BillingCycleUsageResponse_apiCallsBillable(
                    count = 56, 
                    last_updated = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), ),
        )
        """

    def testDailyUsageResponse(self):
        """Test DailyUsageResponse"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
