# coding: utf-8

"""
    UniCourt Enterprise APIs

    <button><a href=\"/developers/enterpriseapi/api/download/UniCourt-Enterprise-API-Spec.yaml\" >Download UniCourt Enterprise APIs Specification</a></button> 

    The version of the OpenAPI document: 
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from unicourt.models.case_update_pacer_options_additional_page_array_inner import CaseUpdatePacerOptionsAdditionalPageArrayInner

class TestCaseUpdatePacerOptionsAdditionalPageArrayInner(unittest.TestCase):
    """CaseUpdatePacerOptionsAdditionalPageArrayInner unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> CaseUpdatePacerOptionsAdditionalPageArrayInner:
        """Test CaseUpdatePacerOptionsAdditionalPageArrayInner
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `CaseUpdatePacerOptionsAdditionalPageArrayInner`
        """
        model = CaseUpdatePacerOptionsAdditionalPageArrayInner()
        if include_optional:
            return CaseUpdatePacerOptionsAdditionalPageArrayInner(
                page = 'associatedCases',
                fetch_if_older_than_days = 0
            )
        else:
            return CaseUpdatePacerOptionsAdditionalPageArrayInner(
        )
        """

    def testCaseUpdatePacerOptionsAdditionalPageArrayInner(self):
        """Test CaseUpdatePacerOptionsAdditionalPageArrayInner"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
