# coding: utf-8

"""
    UniCourt Enterprise APIs

    <button><a href=\"/developers/enterpriseapi/api/download/UniCourt-Enterprise-API-Spec.yaml\" >Download UniCourt Enterprise APIs Specification</a></button> 

    The version of the OpenAPI document: 
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from unicourt.models.preview_document import PreviewDocument

class TestPreviewDocument(unittest.TestCase):
    """PreviewDocument unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> PreviewDocument:
        """Test PreviewDocument
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `PreviewDocument`
        """
        model = PreviewDocument()
        if include_optional:
            return PreviewDocument(
                object = 'PreviewDocument',
                in_library = True,
                added_to_library_date = '0123456789101112131415161718192021222324',
                download_api = ''
            )
        else:
            return PreviewDocument(
                object = 'PreviewDocument',
                in_library = True,
                added_to_library_date = '0123456789101112131415161718192021222324',
                download_api = '',
        )
        """

    def testPreviewDocument(self):
        """Test PreviewDocument"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
