# coding: utf-8

"""
    UniCourt Enterprise APIs

    <button><a href=\"/developers/enterpriseapi/api/download/UniCourt-Enterprise-API-Spec.yaml\" >Download UniCourt Enterprise APIs Specification</a></button> 

    The version of the OpenAPI document: 
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from unicourt.models.judge_type_response import JudgeTypeResponse

class TestJudgeTypeResponse(unittest.TestCase):
    """JudgeTypeResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> JudgeTypeResponse:
        """Test JudgeTypeResponse
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `JudgeTypeResponse`
        """
        model = JudgeTypeResponse()
        if include_optional:
            return JudgeTypeResponse(
                object = 'JudgeTypeResponse',
                judge_type_array = [
                    unicourt.models.judge_type.JudgeType(
                        object = 'JudgeType', 
                        judge_type_id = '01234567891011121314151617', 
                        name = '0', 
                        created_date = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), )
                    ],
                next_page_api = '0',
                previous_page_api = '0',
                page_number = 1,
                total_pages = 1,
                total_count = 1
            )
        else:
            return JudgeTypeResponse(
                object = 'JudgeTypeResponse',
                judge_type_array = [
                    unicourt.models.judge_type.JudgeType(
                        object = 'JudgeType', 
                        judge_type_id = '01234567891011121314151617', 
                        name = '0', 
                        created_date = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), )
                    ],
                next_page_api = '0',
                previous_page_api = '0',
                page_number = 1,
                total_pages = 1,
                total_count = 1,
        )
        """

    def testJudgeTypeResponse(self):
        """Test JudgeTypeResponse"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
