# coding: utf-8

"""
    UniCourt Enterprise APIs

    <button><a href=\"/developers/enterpriseapi/api/download/UniCourt-Enterprise-API-Spec.yaml\" >Download UniCourt Enterprise APIs Specification</a></button> 

    The version of the OpenAPI document: 
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from unicourt.models.case_count_analytics_by_norm_judge_response import CaseCountAnalyticsByNormJudgeResponse

class TestCaseCountAnalyticsByNormJudgeResponse(unittest.TestCase):
    """CaseCountAnalyticsByNormJudgeResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> CaseCountAnalyticsByNormJudgeResponse:
        """Test CaseCountAnalyticsByNormJudgeResponse
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `CaseCountAnalyticsByNormJudgeResponse`
        """
        model = CaseCountAnalyticsByNormJudgeResponse()
        if include_optional:
            return CaseCountAnalyticsByNormJudgeResponse(
                object = 'CaseCountAnalyticsByNormJudgeResponse',
                results = [
                    unicourt.models.case_count_analytics_by_norm_judge.CaseCountAnalyticsByNormJudge(
                        object = 'CaseCountAnalyticsByNormJudge', 
                        norm_judge_id = '01234567891011121314151617', 
                        norm_judge_name = '', 
                        case_search_api = '', 
                        case_count = 56, )
                    ],
                next_page_api = '',
                previous_page_api = '',
                total_pages = 56,
                total_case_count = 56,
                total_norm_judge_count = 56
            )
        else:
            return CaseCountAnalyticsByNormJudgeResponse(
                object = 'CaseCountAnalyticsByNormJudgeResponse',
                results = [
                    unicourt.models.case_count_analytics_by_norm_judge.CaseCountAnalyticsByNormJudge(
                        object = 'CaseCountAnalyticsByNormJudge', 
                        norm_judge_id = '01234567891011121314151617', 
                        norm_judge_name = '', 
                        case_search_api = '', 
                        case_count = 56, )
                    ],
                next_page_api = '',
                previous_page_api = '',
                total_pages = 56,
                total_case_count = 56,
                total_norm_judge_count = 56,
        )
        """

    def testCaseCountAnalyticsByNormJudgeResponse(self):
        """Test CaseCountAnalyticsByNormJudgeResponse"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
