# coding: utf-8

"""
    UniCourt Enterprise APIs

    <button><a href=\"/developers/enterpriseapi/api/download/UniCourt-Enterprise-API-Spec.yaml\" >Download UniCourt Enterprise APIs Specification</a></button> 

    The version of the OpenAPI document: 
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from unicourt.models.pacer_search_receipt import PACERSearchReceipt

class TestPACERSearchReceipt(unittest.TestCase):
    """PACERSearchReceipt unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> PACERSearchReceipt:
        """Test PACERSearchReceipt
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `PACERSearchReceipt`
        """
        model = PACERSearchReceipt()
        if include_optional:
            return PACERSearchReceipt(
                object = 'PACERSearchReceipt',
                transaction_date = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
                search_fee = '012',
                billable_pages = 56,
                login_id = '',
                client_code = '',
                firm_id = '',
                search = '',
                description = '',
                cso_id = 56,
                report_id = ''
            )
        else:
            return PACERSearchReceipt(
                object = 'PACERSearchReceipt',
                transaction_date = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
                search_fee = '012',
                billable_pages = 56,
                login_id = '',
                client_code = '',
                firm_id = '',
                search = '',
                description = '',
                cso_id = 56,
                report_id = '',
        )
        """

    def testPACERSearchReceipt(self):
        """Test PACERSearchReceipt"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
