# coding: utf-8

"""
    UniCourt Enterprise APIs

    <button><a href=\"/developers/enterpriseapi/api/download/UniCourt-Enterprise-API-Spec.yaml\" >Download UniCourt Enterprise APIs Specification</a></button> 

    The version of the OpenAPI document: 
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from unicourt.models.judge_analytics_api import JudgeAnalyticsAPI

class TestJudgeAnalyticsAPI(unittest.TestCase):
    """JudgeAnalyticsAPI unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> JudgeAnalyticsAPI:
        """Test JudgeAnalyticsAPI
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `JudgeAnalyticsAPI`
        """
        model = JudgeAnalyticsAPI()
        if include_optional:
            return JudgeAnalyticsAPI(
                object = 'JudgeAnalyticsAPI',
                norm_judge_api = '',
                associated_norm_attorneys_api = '',
                associated_norm_law_firms_api = '',
                associated_norm_parties_api = ''
            )
        else:
            return JudgeAnalyticsAPI(
                object = 'JudgeAnalyticsAPI',
                norm_judge_api = '',
                associated_norm_attorneys_api = '',
                associated_norm_law_firms_api = '',
                associated_norm_parties_api = '',
        )
        """

    def testJudgeAnalyticsAPI(self):
        """Test JudgeAnalyticsAPI"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
