# coding: utf-8

"""
    UniCourt Enterprise APIs

    <button><a href=\"/developers/enterpriseapi/api/download/UniCourt-Enterprise-API-Spec.yaml\" >Download UniCourt Enterprise APIs Specification</a></button> 

    The version of the OpenAPI document: 
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from unicourt.api.case_search_api import CaseSearchApi


class TestCaseSearchApi(unittest.TestCase):
    """CaseSearchApi unit test stubs"""

    def setUp(self) -> None:
        self.api = CaseSearchApi()

    def tearDown(self) -> None:
        pass

    def test_search_cases(self) -> None:
        """Test case for search_cases

        Case search.
        """
        pass

    def test_search_cases_by_id(self) -> None:
        """Test case for search_cases_by_id

        Case search results for a given caseSearchId.
        """
        pass


if __name__ == '__main__':
    unittest.main()
