# coding: utf-8

"""
    UniCourt Enterprise APIs

    <button><a href=\"/developers/enterpriseapi/api/download/UniCourt-Enterprise-API-Spec.yaml\" >Download UniCourt Enterprise APIs Specification</a></button> 

    The version of the OpenAPI document: 
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from unicourt.models.source_charge import SourceCharge

class TestSourceCharge(unittest.TestCase):
    """SourceCharge unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> SourceCharge:
        """Test SourceCharge
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `SourceCharge`
        """
        model = SourceCharge()
        if include_optional:
            return SourceCharge(
                object = 'SourceCharge',
                source_charge_raw = '',
                source_charge = '',
                is_visible = True,
                source_statute = '',
                source_charge_degree = '',
                source_charge_severity = '',
                source_charge_additional_data_array = [
                    unicourt.models.source_charge_additional_data.SourceChargeAdditionalData(
                        object = 'SourceChargeAdditionalData', 
                        type = '', 
                        value = '', )
                    ],
                first_fetch_date = '0123456789101112131415161718192021222324',
                last_fetch_date = '0123456789101112131415161718192021222324'
            )
        else:
            return SourceCharge(
                object = 'SourceCharge',
                source_charge_raw = '',
                source_charge = '',
                is_visible = True,
                source_statute = '',
                source_charge_degree = '',
                source_charge_severity = '',
                source_charge_additional_data_array = [
                    unicourt.models.source_charge_additional_data.SourceChargeAdditionalData(
                        object = 'SourceChargeAdditionalData', 
                        type = '', 
                        value = '', )
                    ],
                first_fetch_date = '0123456789101112131415161718192021222324',
                last_fetch_date = '0123456789101112131415161718192021222324',
        )
        """

    def testSourceCharge(self):
        """Test SourceCharge"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
