# coding: utf-8

"""
    UniCourt Enterprise APIs

    <button><a href=\"/developers/enterpriseapi/api/download/UniCourt-Enterprise-API-Spec.yaml\" >Download UniCourt Enterprise APIs Specification</a></button> 

    The version of the OpenAPI document: 
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from unicourt.models.case_count_analytics_by_case_filed_date import CaseCountAnalyticsByCaseFiledDate

class TestCaseCountAnalyticsByCaseFiledDate(unittest.TestCase):
    """CaseCountAnalyticsByCaseFiledDate unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> CaseCountAnalyticsByCaseFiledDate:
        """Test CaseCountAnalyticsByCaseFiledDate
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `CaseCountAnalyticsByCaseFiledDate`
        """
        model = CaseCountAnalyticsByCaseFiledDate()
        if include_optional:
            return CaseCountAnalyticsByCaseFiledDate(
                object = 'CaseCountAnalyticsByCaseFiledDate',
                case_count = 56,
                case_search_api = '',
                grouped_by = 'Yearly',
                year = 56,
                quarter = 'Q1',
                month_string = 'January',
                month_int = 56,
                week_of_year = 56,
                week_of_month = 56
            )
        else:
            return CaseCountAnalyticsByCaseFiledDate(
                object = 'CaseCountAnalyticsByCaseFiledDate',
                case_count = 56,
                case_search_api = '',
                grouped_by = 'Yearly',
                year = 56,
                quarter = 'Q1',
                month_string = 'January',
                month_int = 56,
                week_of_year = 56,
                week_of_month = 56,
        )
        """

    def testCaseCountAnalyticsByCaseFiledDate(self):
        """Test CaseCountAnalyticsByCaseFiledDate"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
