# coding: utf-8

"""
    UniCourt Enterprise APIs

    <button><a href=\"/developers/enterpriseapi/api/download/UniCourt-Enterprise-API-Spec.yaml\" >Download UniCourt Enterprise APIs Specification</a></button> 

    The version of the OpenAPI document: 
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from unicourt.models.norm_judge_public_data_name_history_array_inner import NormJudgePublicDataNameHistoryArrayInner

class TestNormJudgePublicDataNameHistoryArrayInner(unittest.TestCase):
    """NormJudgePublicDataNameHistoryArrayInner unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> NormJudgePublicDataNameHistoryArrayInner:
        """Test NormJudgePublicDataNameHistoryArrayInner
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `NormJudgePublicDataNameHistoryArrayInner`
        """
        model = NormJudgePublicDataNameHistoryArrayInner()
        if include_optional:
            return NormJudgePublicDataNameHistoryArrayInner(
                first_name = '',
                middle_name = '',
                last_name = '',
                prefix = '',
                suffix = '',
                is_visible = True
            )
        else:
            return NormJudgePublicDataNameHistoryArrayInner(
                first_name = '',
                middle_name = '',
                last_name = '',
                prefix = '',
                suffix = '',
                is_visible = True,
        )
        """

    def testNormJudgePublicDataNameHistoryArrayInner(self):
        """Test NormJudgePublicDataNameHistoryArrayInner"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
