# coding: utf-8

"""
    UniCourt Enterprise APIs

    <button><a href=\"/developers/enterpriseapi/api/download/UniCourt-Enterprise-API-Spec.yaml\" >Download UniCourt Enterprise APIs Specification</a></button> 

    The version of the OpenAPI document: 
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from unicourt.models.court_system import CourtSystem

class TestCourtSystem(unittest.TestCase):
    """CourtSystem unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> CourtSystem:
        """Test CourtSystem
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `CourtSystem`
        """
        model = CourtSystem()
        if include_optional:
            return CourtSystem(
                object = 'CourtSystem',
                court_type_id = '01234567891011121314151617',
                court_system_id = '01234567891011121314151617',
                court_type = '0',
                name = '0',
                created_date = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f')
            )
        else:
            return CourtSystem(
                object = 'CourtSystem',
                court_type_id = '01234567891011121314151617',
                court_system_id = '01234567891011121314151617',
                court_type = '0',
                name = '0',
                created_date = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
        )
        """

    def testCourtSystem(self):
        """Test CourtSystem"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
