# coding: utf-8

"""
    UniCourt Enterprise APIs

    <button><a href=\"/developers/enterpriseapi/api/download/UniCourt-Enterprise-API-Spec.yaml\" >Download UniCourt Enterprise APIs Specification</a></button> 

    The version of the OpenAPI document: 
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from unicourt.api.case_update_api import CaseUpdateApi


class TestCaseUpdateApi(unittest.TestCase):
    """CaseUpdateApi unit test stubs"""

    def setUp(self) -> None:
        self.api = CaseUpdateApi()

    def tearDown(self) -> None:
        pass

    def test_get_case_update_by_case_id(self) -> None:
        """Test case for get_case_update_by_case_id

        Get Case Updates for a requested CaseId.
        """
        pass

    def test_get_case_updates(self) -> None:
        """Test case for get_case_updates

        Get Case Update  list for a requested Date.
        """
        pass

    def test_update_case(self) -> None:
        """Test case for update_case

        Add Case Update for the requested Case Id.
        """
        pass


if __name__ == '__main__':
    unittest.main()
