# coding: utf-8

"""
    UniCourt Enterprise APIs

    <button><a href=\"/developers/enterpriseapi/api/download/UniCourt-Enterprise-API-Spec.yaml\" >Download UniCourt Enterprise APIs Specification</a></button> 

    The version of the OpenAPI document: 
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from unicourt.models.case_document_order_request import CaseDocumentOrderRequest

class TestCaseDocumentOrderRequest(unittest.TestCase):
    """CaseDocumentOrderRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> CaseDocumentOrderRequest:
        """Test CaseDocumentOrderRequest
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `CaseDocumentOrderRequest`
        """
        model = CaseDocumentOrderRequest()
        if include_optional:
            return CaseDocumentOrderRequest(
                case_document_id = '01234567891011121314151617',
                is_preview_only = True,
                pacer_options = unicourt.models.case_document_order_pacer_options.CaseDocumentOrderPacerOptions(
                    pacer_user_id = '012345', 
                    pacer_client_code = '', )
            )
        else:
            return CaseDocumentOrderRequest(
                case_document_id = '01234567891011121314151617',
                is_preview_only = True,
        )
        """

    def testCaseDocumentOrderRequest(self):
        """Test CaseDocumentOrderRequest"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
