# coding: utf-8

"""
    UniCourt Enterprise APIs

    <button><a href=\"/developers/enterpriseapi/api/download/UniCourt-Enterprise-API-Spec.yaml\" >Download UniCourt Enterprise APIs Specification</a></button> 

    The version of the OpenAPI document: 
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from unicourt.models.case_cause_of_action import CaseCauseOfAction

class TestCaseCauseOfAction(unittest.TestCase):
    """CaseCauseOfAction unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> CaseCauseOfAction:
        """Test CaseCauseOfAction
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `CaseCauseOfAction`
        """
        model = CaseCauseOfAction()
        if include_optional:
            return CaseCauseOfAction(
                object = 'CaseCauseOfAction',
                cause_of_action = unicourt.models.cause_of_action.CauseOfAction(
                    object = 'CauseOfAction', 
                    cause_of_action_id = '01234567891011121314151617', 
                    cause_of_action_group_id = '01234567891011121314151617', 
                    cause_of_action_group = '0', 
                    name = '0', 
                    created_date = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), ),
                cause_of_action_additional_data_array = [
                    unicourt.models.cause_of_action_additional_data.CauseOfActionAdditionalData(
                        object = 'CauseOfActionAdditionalData', 
                        cause_of_action_additional_data_id = '01234567891011121314151617', 
                        type = '0', 
                        value = '0', 
                        created_date = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), )
                    ]
            )
        else:
            return CaseCauseOfAction(
                object = 'CaseCauseOfAction',
                cause_of_action = unicourt.models.cause_of_action.CauseOfAction(
                    object = 'CauseOfAction', 
                    cause_of_action_id = '01234567891011121314151617', 
                    cause_of_action_group_id = '01234567891011121314151617', 
                    cause_of_action_group = '0', 
                    name = '0', 
                    created_date = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), ),
                cause_of_action_additional_data_array = [
                    unicourt.models.cause_of_action_additional_data.CauseOfActionAdditionalData(
                        object = 'CauseOfActionAdditionalData', 
                        cause_of_action_additional_data_id = '01234567891011121314151617', 
                        type = '0', 
                        value = '0', 
                        created_date = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), )
                    ],
        )
        """

    def testCaseCauseOfAction(self):
        """Test CaseCauseOfAction"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
