# coding: utf-8

"""
    UniCourt Enterprise APIs

    <button><a href=\"/developers/enterpriseapi/api/download/UniCourt-Enterprise-API-Spec.yaml\" >Download UniCourt Enterprise APIs Specification</a></button> 

    The version of the OpenAPI document: 
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from unicourt.models.possible_norm_law_firm import PossibleNormLawFirm

class TestPossibleNormLawFirm(unittest.TestCase):
    """PossibleNormLawFirm unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> PossibleNormLawFirm:
        """Test PossibleNormLawFirm
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `PossibleNormLawFirm`
        """
        model = PossibleNormLawFirm()
        if include_optional:
            return PossibleNormLawFirm(
                object = 'PossibleNormLawFirm',
                norm_law_firm_id = '01234567891011121314151617',
                norm_law_firm_name = '',
                best_match = True,
                source_details = unicourt.models.possible_norm_law_firm_source_details.PossibleNormLawFirm_sourceDetails(
                    source = 'Case_Attorney_Linked_In_Other_Cases', 
                    linked_norm_attorney_id_array = [
                        '01234567891011121314151617'
                        ], ),
                confidence_score = 1.337,
                score_constituents = unicourt.models.possible_norm_law_firm_score_constituents.PossibleNormLawFirm_scoreConstituents(
                    name_similarity_score = 1.337, 
                    other_potential_norm_law_firms = 56, 
                    secretary_of_state_id = 'Matched', 
                    address = 'Matched', 
                    email = 'Matched', 
                    phone = 'Matched', ),
                norm_law_firm_api = '',
                associated_norm_attorney_api = '',
                associated_norm_judge_api = '',
                associated_norm_parties_api = '',
                case_count_analytics_by_norm_law_firm_api = '',
                case_count_analytics_by_opposing_norm_law_firm_api = ''
            )
        else:
            return PossibleNormLawFirm(
                object = 'PossibleNormLawFirm',
                norm_law_firm_id = '01234567891011121314151617',
                norm_law_firm_name = '',
                best_match = True,
                source_details = unicourt.models.possible_norm_law_firm_source_details.PossibleNormLawFirm_sourceDetails(
                    source = 'Case_Attorney_Linked_In_Other_Cases', 
                    linked_norm_attorney_id_array = [
                        '01234567891011121314151617'
                        ], ),
                confidence_score = 1.337,
                score_constituents = unicourt.models.possible_norm_law_firm_score_constituents.PossibleNormLawFirm_scoreConstituents(
                    name_similarity_score = 1.337, 
                    other_potential_norm_law_firms = 56, 
                    secretary_of_state_id = 'Matched', 
                    address = 'Matched', 
                    email = 'Matched', 
                    phone = 'Matched', ),
                norm_law_firm_api = '',
                associated_norm_attorney_api = '',
                associated_norm_judge_api = '',
                associated_norm_parties_api = '',
                case_count_analytics_by_norm_law_firm_api = '',
                case_count_analytics_by_opposing_norm_law_firm_api = '',
        )
        """

    def testPossibleNormLawFirm(self):
        """Test PossibleNormLawFirm"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
