# coding: utf-8

"""
    UniCourt Enterprise APIs

    <button><a href=\"/developers/enterpriseapi/api/download/UniCourt-Enterprise-API-Spec.yaml\" >Download UniCourt Enterprise APIs Specification</a></button> 

    The version of the OpenAPI document: 
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from unicourt.models.case_export_callback import CaseExportCallback

class TestCaseExportCallback(unittest.TestCase):
    """CaseExportCallback unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> CaseExportCallback:
        """Test CaseExportCallback
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `CaseExportCallback`
        """
        model = CaseExportCallback()
        if include_optional:
            return CaseExportCallback(
                object = 'CaseExportCallback',
                case_export_callback_id = '01234567891011121314151617',
                case_id = '01234567891011121314151617',
                callback_generated_date = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
                status = 'COMPLETE',
                case_export_callback_api = '0',
                file = unicourt.models.export_file.ExportFile(
                    object = 'ExportFile', 
                    name = '0', 
                    expiry_date = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                    file_url = '0', ),
                exception = unicourt.models.exception.Exception(
                    object = 'Exception', 
                    code = '0', 
                    message = '0', 
                    details = '0', )
            )
        else:
            return CaseExportCallback(
                object = 'CaseExportCallback',
                case_export_callback_id = '01234567891011121314151617',
                case_id = '01234567891011121314151617',
                callback_generated_date = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
                status = 'COMPLETE',
                case_export_callback_api = '0',
                file = unicourt.models.export_file.ExportFile(
                    object = 'ExportFile', 
                    name = '0', 
                    expiry_date = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                    file_url = '0', ),
                exception = unicourt.models.exception.Exception(
                    object = 'Exception', 
                    code = '0', 
                    message = '0', 
                    details = '0', ),
        )
        """

    def testCaseExportCallback(self):
        """Test CaseExportCallback"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
