# coding: utf-8

"""
    UniCourt Enterprise APIs

    <button><a href=\"/developers/enterpriseapi/api/download/UniCourt-Enterprise-API-Spec.yaml\" >Download UniCourt Enterprise APIs Specification</a></button> 

    The version of the OpenAPI document: 
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from unicourt.models.bar_source_data_statewide_grievance_committee_history_array_inner import BarSourceDataStatewideGrievanceCommitteeHistoryArrayInner

class TestBarSourceDataStatewideGrievanceCommitteeHistoryArrayInner(unittest.TestCase):
    """BarSourceDataStatewideGrievanceCommitteeHistoryArrayInner unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> BarSourceDataStatewideGrievanceCommitteeHistoryArrayInner:
        """Test BarSourceDataStatewideGrievanceCommitteeHistoryArrayInner
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `BarSourceDataStatewideGrievanceCommitteeHistoryArrayInner`
        """
        model = BarSourceDataStatewideGrievanceCommitteeHistoryArrayInner()
        if include_optional:
            return BarSourceDataStatewideGrievanceCommitteeHistoryArrayInner(
                final_decision = '',
                final_decision_date = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
                grievance_complaint_number = '',
                public_comments = ''
            )
        else:
            return BarSourceDataStatewideGrievanceCommitteeHistoryArrayInner(
                final_decision = '',
                final_decision_date = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
                grievance_complaint_number = '',
                public_comments = '',
        )
        """

    def testBarSourceDataStatewideGrievanceCommitteeHistoryArrayInner(self):
        """Test BarSourceDataStatewideGrievanceCommitteeHistoryArrayInner"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
