# coding: utf-8

"""
    UniCourt Enterprise APIs

    <button><a href=\"/developers/enterpriseapi/api/download/UniCourt-Enterprise-API-Spec.yaml\" >Download UniCourt Enterprise APIs Specification</a></button> 

    The version of the OpenAPI document: 
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from unicourt.models.billing_cycle_usage_response_api_calls_made import BillingCycleUsageResponseApiCallsMade

class TestBillingCycleUsageResponseApiCallsMade(unittest.TestCase):
    """BillingCycleUsageResponseApiCallsMade unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> BillingCycleUsageResponseApiCallsMade:
        """Test BillingCycleUsageResponseApiCallsMade
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `BillingCycleUsageResponseApiCallsMade`
        """
        model = BillingCycleUsageResponseApiCallsMade()
        if include_optional:
            return BillingCycleUsageResponseApiCallsMade(
                count = 56,
                last_updated = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f')
            )
        else:
            return BillingCycleUsageResponseApiCallsMade(
                count = 56,
                last_updated = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
        )
        """

    def testBillingCycleUsageResponseApiCallsMade(self):
        """Test BillingCycleUsageResponseApiCallsMade"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
