# coding: utf-8

"""
    UniCourt Enterprise APIs

    <button><a href=\"/developers/enterpriseapi/api/download/UniCourt-Enterprise-API-Spec.yaml\" >Download UniCourt Enterprise APIs Specification</a></button> 

    The version of the OpenAPI document: 
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from unicourt.models.case_document import CaseDocument

class TestCaseDocument(unittest.TestCase):
    """CaseDocument unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> CaseDocument:
        """Test CaseDocument
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `CaseDocument`
        """
        model = CaseDocument()
        if include_optional:
            return CaseDocument(
                object = 'CaseDocument',
                case_document_id = '01234567891011121314151617',
                sort_order = 56,
                name = '',
                description = '',
                document_filed_date = '0123456789101112131415161718192021222324',
                parent_document_id = '01234567891011121314151617',
                child_document_id_array = [
                    '01234567891011121314151617'
                    ],
                pages = 56,
                is_preview_available = True,
                preview_document = unicourt.models.preview_document.PreviewDocument(
                    object = 'PreviewDocument', 
                    in_library = True, 
                    added_to_library_date = '0123456789101112131415161718192021222324', 
                    download_api = '', ),
                price = 1.337,
                in_library = True,
                added_to_library_date = '0123456789101112131415161718192021222324',
                estimated_order_duration = 'estimateUnavailable',
                download_api = '',
                first_fetch_date = '0123456789101112131415161718192021222324',
                source_data_status = 'NO_LONGER_AVAILABLE_IN_COURT'
            )
        else:
            return CaseDocument(
                object = 'CaseDocument',
                case_document_id = '01234567891011121314151617',
                sort_order = 56,
                name = '',
                description = '',
                document_filed_date = '0123456789101112131415161718192021222324',
                parent_document_id = '01234567891011121314151617',
                child_document_id_array = [
                    '01234567891011121314151617'
                    ],
                pages = 56,
                is_preview_available = True,
                preview_document = unicourt.models.preview_document.PreviewDocument(
                    object = 'PreviewDocument', 
                    in_library = True, 
                    added_to_library_date = '0123456789101112131415161718192021222324', 
                    download_api = '', ),
                price = 1.337,
                in_library = True,
                added_to_library_date = '0123456789101112131415161718192021222324',
                estimated_order_duration = 'estimateUnavailable',
                download_api = '',
                first_fetch_date = '0123456789101112131415161718192021222324',
                source_data_status = 'NO_LONGER_AVAILABLE_IN_COURT',
        )
        """

    def testCaseDocument(self):
        """Test CaseDocument"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
