# coding: utf-8

"""
    UniCourt Enterprise APIs

    <button><a href=\"/developers/enterpriseapi/api/download/UniCourt-Enterprise-API-Spec.yaml\" >Download UniCourt Enterprise APIs Specification</a></button> 

    The version of the OpenAPI document: 
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from unicourt.models.pacer_credential_list_response import PacerCredentialListResponse

class TestPacerCredentialListResponse(unittest.TestCase):
    """PacerCredentialListResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> PacerCredentialListResponse:
        """Test PacerCredentialListResponse
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `PacerCredentialListResponse`
        """
        model = PacerCredentialListResponse()
        if include_optional:
            return PacerCredentialListResponse(
                object = 'PacerCredentialListResponse',
                total_pages = 56,
                total_count = 56,
                page_number = 56,
                next_page_api = '0',
                previous_page_api = '0',
                pacer_credential_array = [
                    unicourt.models.pacer_credential.PacerCredential(
                        object = 'PacerCredential', 
                        pacer_user_id = '012345', 
                        default_pacer_client_code = '', )
                    ]
            )
        else:
            return PacerCredentialListResponse(
                object = 'PacerCredentialListResponse',
                total_pages = 56,
                total_count = 56,
                page_number = 56,
                next_page_api = '0',
                previous_page_api = '0',
                pacer_credential_array = [
                    unicourt.models.pacer_credential.PacerCredential(
                        object = 'PacerCredential', 
                        pacer_user_id = '012345', 
                        default_pacer_client_code = '', )
                    ],
        )
        """

    def testPacerCredentialListResponse(self):
        """Test PacerCredentialListResponse"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
