import os
import pickle
import unicourt
from unicourt import Authentication, CaseDocket, CaseSearch
from utility import generate_json_file_from_unicourt_obj, load_unicourt_obj_from_json_file

unicourt.CLIENT_ID = os.getenv("CLIENT_ID")
unicourt.CLIENT_SECRET = os.getenv("CLIENT_SECRET")
auth_obj, http_status_code = Authentication.generate_new_token()

try:
    business = "motors"

    # Execute Case-Search Request
    cases, statuses = CaseSearch.search_cases(q=f'caseName:({business})', order='desc', sort='filedDate', page_number=1)

    case, status = CaseDocket.get_case(cases['case_search_result_array'][0]['case_id']) # also supports cases.case_search_result_array[0].case_id

    print("The case object:")
    print(case)

    # To pickle the case object or to store the object in file and re-load
    # 1. Convert the object in dict using `to_dict()` and then pickle it
    with open('testpickle.pkl', 'wb') as file:
        pickle.dump(case.to_dict(), file)

    with open('testpickle.pkl', 'rb') as file:
        loaded_object = pickle.load(file)

    # 2. Create a wrapper for storing the object to file and retrieve it.
    generate_json_file_from_unicourt_obj(case, 'casefile.json')
    new_case = load_unicourt_obj_from_json_file('casefile.json')
except Exception as e:
    print(e)

# # Invalidate the generated access token
Authentication.invalidate_token()

# <class 'unicourt.model.case.Case'>
# Object for the above print is a raw json object
# {'attorneys': {'attorney_array': [],
#                'next_page_api': None,
#                'object': 'Attorneys',
#                'page_number': 1,
#                'total_count': 0,
#                'total_pages': 0},
#  'case_documents': {'case_document_array': [],
#                     'next_page_api': None,
#                     'object': 'CaseDocuments',
#                     'page_number': 1,
#                     'total_count': 0,
#                     'total_pages': 0},
#  'case_id': 'CASEofd763d32e1a8f',
#  'case_name': 'The People of the State of California vs. ALOHA MOTORS',
#  'case_number': '24TR019236',
#  'case_stats': {'all_case_document_count': 0,
#                 'attorney_count': 0,
#                 'case_document_in_library_count': 0,
#                 'docket_entry_count': 3,
#                 'free_case_document_count': 0,
#                 'hearing_count': 0,
#                 'judge_count': 0,
#                 'object': 'CaseStats',
#                 'paid_case_document_count': 0,
#                 'party_count': 4,
#                 'related_case_count': 0},
#  'case_status': {'case_class_array': ['Civil', 'Criminal'],
#                  'case_status_group': 'Open',
#                  'case_status_group_id': 'CSSGCYoBCJ3A8j4MX4',
#                  'case_status_id': 'CSSTVnE3shD3CGtkcZ',
#                  'created_date': '2022-03-28 04:58:47+00:00',
#                  'name': 'Open',
#                  'object': 'CaseStatus'},
#  'case_type': {'area_of_law': None,
#                'area_of_law_id': None,
#                'case_class': 'Traffic',
#                'case_class_id': 'CSCL9HZEekKPKFDg4i',
#                'case_type_group': None,
#                'case_type_group_id': None,
#                'case_type_id': 'CTYP9HZEekKPKFDg4i',
#                'case_type_tag': None,
#                'created_date': '2022-10-12 11:00:47+00:00',
#                'name': None,
#                'object': 'CaseType',
#                'sali_code': None},
#  'cause_of_action_array': [],
#  'charge_array': [],
#  'court': {'additional_levels': None,
#            'appeal_courts_for_court_api': 'https://enterpriseapi.unicourt.com/masterData/court/CORTmxapugRc4PeotS/appealCourts',
#            'container': None,
#            'container_type': None,
#            'court_id': 'CORTmxapugRc4PeotS',
#            'court_locations_for_court_api': 'https://enterpriseapi.unicourt.com/masterData/court/CORTmxapugRc4PeotS/courtLocations',
#            'court_service_status_api': 'https://enterpriseapi.unicourt.com/masterData/courtServiceStatus?q=Court%3A%28courtId%3A%22CORTmxapugRc4PeotS%22%29',
#            'court_system_id': 'COSYACHBdMewtaG5DY',
#            'court_type_id': 'COTPm8jjc2PAydpFhq',
#            'created_date': '2024-05-13 11:56:43+00:00',
#            'jurisdiction_geo_for_court_api': 'https://enterpriseapi.unicourt.com/masterData/court/CORTmxapugRc4PeotS/jurisdictionGeo',
#            'name': 'Monterey County Superior Court',
#            'name_aka': 'Monterey County Superior Court of California',
#            'object': 'Court',
#            'system': 'California Superior Courts',
#            'type': 'State'},
#  'court_location': {'city': 'Salinas',
#                     'court_location_id': 'COLOkakwgDxCyaZkx3',
#                     'court_service_status_api': 'https://enterpriseapi.unicourt.com/masterData/courtServiceStatus?q=CourtLocation%3A%28courtLocationId%3A%22COLOkakwgDxCyaZkx3%22%29',
#                     'courts_for_court_location_api': 'https://enterpriseapi.unicourt.com/masterData/courtLocation/COLOkakwgDxCyaZkx3/courts',
#                     'created_date': '2024-05-13 11:56:43+00:00',
#                     'name': 'Salinas Courthouse',
#                     'object': 'CourtLocation',
#                     'state_name': 'California',
#                     'street_address1': '240 Church St',
#                     'street_address2': None},
#  'court_service_status_api': 'https://enterpriseapi.unicourt.com/masterData/courtServiceStatus/CTSSac1a9637213f30',
#  'court_service_status_id': 'CTSSac1a9637213f30',
#  'docket_entries': {'docket_entry_array': [{'boundary': 'first',
#                                             'docket_badge': 'DOCKET',
#                                             'docket_entry_date': '2024-07-22 '
#                                                                  '00:00:00-07:00',
#                                             'docket_entry_primary_documents': {'case_document_array': [],
#                                                                                'next_page_api': None,
#                                                                                'object': 'DocketEntryPrimaryDocuments',
#                                                                                'page_number': 1,
#                                                                                'total_count': 0,
#                                                                                'total_pages': 0},
#                                             'docket_entry_secondary_documents': {'case_document_array': [],
#                                                                                  'next_page_api': None,
#                                                                                  'object': 'DocketEntrySecondaryDocuments',
#                                                                                  'page_number': 1,
#                                                                                  'total_count': 0,
#                                                                                  'total_pages': 0},
#                                             'docket_number': None,
#                                             'last_fetch_date': '2024-07-23T04:18:43+00:00',
#                                             'object': 'DocketEntry',
#                                             'referenced_docket_number_array': [],
#                                             'sort_order': 2,
#                                             'text': "File Type: Owner's "
#                                                     'Responsibility Citation',
#                                             'text_structured': {'extracted_fields': None,
#                                                                 'raw_ordered_data_array': [{'child_array': [],
#                                                                                             'lbl': 'File '
#                                                                                                    'Type',
#                                                                                             'ord': 0,
#                                                                                             'val': "Owner's "
#                                                                                                    'Responsibility '
#                                                                                                    'Citation'}]}},
#                                            {'boundary': None,
#                                             'docket_badge': 'DOCKET',
#                                             'docket_entry_date': '2024-07-22 '
#                                                                  '00:00:00-07:00',
#                                             'docket_entry_primary_documents': {'case_document_array': [],
#                                                                                'next_page_api': None,
#                                                                                'object': 'DocketEntryPrimaryDocuments',
#                                                                                'page_number': 1,
#                                                                                'total_count': 0,
#                                                                                'total_pages': 0},
#                                             'docket_entry_secondary_documents': {'case_document_array': [],
#                                                                                  'next_page_api': None,
#                                                                                  'object': 'DocketEntrySecondaryDocuments',
#                                                                                  'page_number': 1,
#                                                                                  'total_count': 0,
#                                                                                  'total_pages': 0},
#                                             'docket_number': None,
#                                             'last_fetch_date': '2024-07-23T04:18:43+00:00',
#                                             'object': 'DocketEntry',
#                                             'referenced_docket_number_array': [],
#                                             'sort_order': 1,
#                                             'text': 'File Type: Citation: '
#                                                     'Unsigned',
#                                             'text_structured': {'extracted_fields': None,
#                                                                 'raw_ordered_data_array': [{'child_array': [],
#                                                                                             'lbl': 'File '
#                                                                                                    'Type',
#                                                                                             'ord': 0,
#                                                                                             'val': 'Citation: '
#                                                                                                    'Unsigned'}]}},
#                                            {'boundary': 'last',
#                                             'docket_badge': 'DOCKET',
#                                             'docket_entry_date': '2024-07-22 '
#                                                                  '00:00:00-07:00',
#                                             'docket_entry_primary_documents': {'case_document_array': [],
#                                                                                'next_page_api': None,
#                                                                                'object': 'DocketEntryPrimaryDocuments',
#                                                                                'page_number': 1,
#                                                                                'total_count': 0,
#                                                                                'total_pages': 0},
#                                             'docket_entry_secondary_documents': {'case_document_array': [],
#                                                                                  'next_page_api': None,
#                                                                                  'object': 'DocketEntrySecondaryDocuments',
#                                                                                  'page_number': 1,
#                                                                                  'total_count': 0,
#                                                                                  'total_pages': 0},
#                                             'docket_number': None,
#                                             'last_fetch_date': '2024-07-23T04:18:43+00:00',
#                                             'object': 'DocketEntry',
#                                             'referenced_docket_number_array': [],
#                                             'sort_order': 0,
#                                             'text': 'File Type: Citation: '
#                                                     'Filed',
#                                             'text_structured': {'extracted_fields': None,
#                                                                 'raw_ordered_data_array': [{'child_array': [],
#                                                                                             'lbl': 'File '
#                                                                                                    'Type',
#                                                                                             'ord': 0,
#                                                                                             'val': 'Citation: '
#                                                                                                    'Filed'}]}}],
#                     'next_page_api': None,
#                     'object': 'DocketEntries',
#                     'page_number': 1,
#                     'total_count': 3,
#                     'total_pages': 1},
#  'export_api': 'https://enterpriseapi.unicourt.com/caseExport/CASEofd763d32e1a8f',
#  'filed_date': '2024-07-22 00:00:00+00:00',
#  'first_fetch_date': '2024-07-23 04:02:59+00:00',
#  'has_documents_with_preview': False,
#  'has_only_meta_info': False,
#  'hearings': {'hearing_array': [],
#               'next_page_api': None,
#               'object': 'Hearings',
#               'page_number': 1,
#               'total_count': 0,
#               'total_pages': 0},
#  'judges': {'judge_array': [],
#             'next_page_api': None,
#             'object': 'Judges',
#             'page_number': 1,
#             'total_count': 0,
#             'total_pages': 0},
#  'last_fetch_date': '2024-07-23 04:03:03+00:00',
#  'last_fetch_date_with_updates': '2024-07-23 04:03:03+00:00',
#  'object': 'Case',
#  'participants_last_fetch_date': '2024-07-23 04:03:03+00:00',
#  'parties': {'next_page_api': None,
#              'object': 'Parties',
#              'page_number': 1,
#              'party_array': [{'attorney_representation_type': None,
#                               'contact': {'address_array': [],
#                                           'email_array': [],
#                                           'object': 'Contact',
#                                           'phone_number_array': []},
#                               'first_fetch_date': '2024-07-23 04:03:00+00:00',
#                               'first_name': 'The People of the State of '
#                                             'California',
#                               'is_visible': True,
#                               'last_fetch_date': '2024-07-23 04:03:00+00:00',
#                               'last_name': None,
#                               'middle_name': None,
#                               'name': 'The People of the State of California',
#                               'name_prefix': '',
#                               'name_suffix': '',
#                               'object': 'Party',
#                               'party_attorney_associations': {'next_page_api': None,
#                                                               'object': 'PartyAttorneyAssociations',
#                                                               'page_number': 1,
#                                                               'party_attorney_association_array': [],
#                                                               'total_count': 0,
#                                                               'total_pages': 0},
#                               'party_classification_type': 'COMPANY',
#                               'party_id': 'PRTYof9d1fe65dfff7',
#                               'party_role': {'created_date': '2022-05-27 '
#                                                              '00:50:36+00:00',
#                                              'description': None,
#                                              'name': 'Plaintiff',
#                                              'object': 'PartyRole',
#                                              'party_role_group': 'Party '
#                                                                  'Offensive',
#                                              'party_role_group_id': 'PTYGBnjxbx6tKNfVEP',
#                                              'party_role_id': 'PTYRiP8nMgPxBsPc5i'},
#                               'possible_norm_party_array': [],
#                               'source_party_role': 'Plaintiff'},
#                              {'attorney_representation_type': None,
#                               'contact': {'address_array': [],
#                                           'email_array': [],
#                                           'object': 'Contact',
#                                           'phone_number_array': []},
#                               'first_fetch_date': '2024-07-23 04:03:01+00:00',
#                               'first_name': 'ALOHA',
#                               'is_visible': True,
#                               'last_fetch_date': '2024-07-23 04:03:02+00:00',
#                               'last_name': 'MOTORS',
#                               'middle_name': None,
#                               'name': 'ALOHA MOTORS',
#                               'name_prefix': None,
#                               'name_suffix': None,
#                               'object': 'Party',
#                               'party_attorney_associations': {'next_page_api': None,
#                                                               'object': 'PartyAttorneyAssociations',
#                                                               'page_number': 1,
#                                                               'party_attorney_association_array': [],
#                                                               'total_count': 0,
#                                                               'total_pages': 0},
#                               'party_classification_type': 'INDIVIDUAL',
#                               'party_id': 'PRTYof3e6bb3705751',
#                               'party_role': {'created_date': '2022-05-27 '
#                                                              '00:50:35+00:00',
#                                              'description': None,
#                                              'name': 'Defendant',
#                                              'object': 'PartyRole',
#                                              'party_role_group': 'Party '
#                                                                  'Defensive',
#                                              'party_role_group_id': 'PTYG73uQdgJdpA3ebc',
#                                              'party_role_id': 'PTYRKo8tkTBFvJdCQp'},
#                               'possible_norm_party_array': [],
#                               'source_party_role': 'Defendant'},
#                              {'attorney_representation_type': None,
#                               'contact': {'address_array': [],
#                                           'email_array': [],
#                                           'object': 'Contact',
#                                           'phone_number_array': []},
#                               'first_fetch_date': '2024-07-23 04:03:01+00:00',
#                               'first_name': 'Kristi',
#                               'is_visible': True,
#                               'last_fetch_date': '2024-07-23 04:03:01+00:00',
#                               'last_name': 'Cho',
#                               'middle_name': None,
#                               'name': 'Kristi Cho',
#                               'name_prefix': None,
#                               'name_suffix': None,
#                               'object': 'Party',
#                               'party_attorney_associations': {'next_page_api': None,
#                                                               'object': 'PartyAttorneyAssociations',
#                                                               'page_number': 1,
#                                                               'party_attorney_association_array': [],
#                                                               'total_count': 0,
#                                                               'total_pages': 0},
#                               'party_classification_type': 'INDIVIDUAL',
#                               'party_id': 'PRTYof6df7a01dd8d3',
#                               'party_role': None,
#                               'possible_norm_party_array': [],
#                               'source_party_role': 'OFFICER'},
#                              {'attorney_representation_type': None,
#                               'contact': {'address_array': [],
#                                           'email_array': [],
#                                           'object': 'Contact',
#                                           'phone_number_array': []},
#                               'first_fetch_date': '2024-07-23 04:03:02+00:00',
#                               'first_name': 'SARAH',
#                               'is_visible': True,
#                               'last_fetch_date': '2024-07-23 04:03:02+00:00',
#                               'last_name': 'SPINDEL',
#                               'middle_name': 'ROSE',
#                               'name': 'SARAH ROSE SPINDEL',
#                               'name_prefix': None,
#                               'name_suffix': None,
#                               'object': 'Party',
#                               'party_attorney_associations': {'next_page_api': None,
#                                                               'object': 'PartyAttorneyAssociations',
#                                                               'page_number': 1,
#                                                               'party_attorney_association_array': [],
#                                                               'total_count': 0,
#                                                               'total_pages': 0},
#                               'party_classification_type': 'INDIVIDUAL',
#                               'party_id': 'PRTYof408cbd2f2f80',
#                               'party_role': None,
#                               'possible_norm_party_array': [],
#                               'source_party_role': 'CITEE'}],
#              'total_count': 4,
#              'total_pages': 1},
#  'related_cases': {'next_page_api': None,
#                    'object': 'RelatedCases',
#                    'page_number': 1,
#                    'related_case_array': [],
#                    'total_count': 0,
#                    'total_pages': 0},
#  'source_case_data': {'nature_of_suit_array': [],
#                       'object': 'SourceCaseData',
#                       'source_case_status': 'ACTIVE',
#                       'source_case_type': 'ADULT TRAFFIC',
#                       'source_cause_of_action_array': [],
#                       'source_charge_array': [],
#                       'source_court': 'NOT PROVIDED',
#                       'source_page_data': [{'additional_source_data': {'extracted_fields': None,
#                                                                        'raw_ordered_data_array': [{'child_array': [],
#                                                                                                    'lbl': 'Type '
#                                                                                                           'id',
#                                                                                                    'ord': 0,
#                                                                                                    'val': 'TR'}]},
#                                             'first_fetch_date': '2024-07-23T04:02:59+00:00',
#                                             'last_fetch_date': '2024-07-23T04:02:59+00:00',
#                                             'object': 'SourcePageData',
#                                             'page_name': 'Case Details'}]},
#  'source_data_status': None,
#  'url': 'https://unicourt.com/case/urc-CASEofd763d32e1a8f'}